# Generated by Django 2.0 on 2018-01-22 09:40
import cloudinary.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth', '0009_alter_user_last_name_max_length')]
    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password'),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={
                            'unique': 'A user with that username already exists.'
                        },
                        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name='username',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        blank=True, max_length=30, verbose_name='first name'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='last name'
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name='email address',
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='date joined',
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('Provider', 'provider'), ('Customer', 'customer')
                        ],
                        max_length=256,
                    ),
                ),
                (
                    'phone_number',
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.Group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.Permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[('objects', django.contrib.auth.models.UserManager())],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'status',
                    models.IntegerField(
                        choices=[
                            (1, 'not started'),
                            (2, 'started'),
                            (3, 'completed'),
                            (5, 'cancelled'),
                        ],
                        default=1,
                    ),
                ),
                ('start', models.DateTimeField()),
                (
                    'price',
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    'customer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='customer',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='provider',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('paid', models.BooleanField()),
                ('order', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('position', models.CharField(max_length=256)),
                ('description', models.TextField()),
                (
                    'company_name',
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    'application_url',
                    models.URLField(blank=True, max_length=256, null=True),
                ),
                ('featured', models.BooleanField()),
                ('cost', models.FloatField()),
                ('hours', models.FloatField()),
                ('expires', models.DateTimeField()),
                ('filled', models.BooleanField()),
                ('num_to_apply', models.IntegerField()),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('selected', models.BooleanField()),
                (
                    'applicant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api.Job',
                    ),
                ),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=256)),
                (
                    'slug',
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from='name'
                    ),
                ),
                ('description', models.TextField()),
                (
                    'parent_category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api.JobCategory',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Category', 'verbose_name_plural': 'Categories'
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=256)),
                (
                    'slug',
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from='name'
                    ),
                ),
                ('description', models.TextField()),
                (
                    'parent_category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api.JobType',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Category', 'verbose_name_plural': 'Categories'
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('address', models.CharField(max_length=120)),
                (
                    'state',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('', 'Select State'),
                            ('Abia', 'Abia'),
                            ('Abuja', 'Abuja'),
                            ('Adamawa', 'Adamawa'),
                            ('Akwa Ibom', 'Akwa Ibom'),
                            ('Anambra', 'Anambra'),
                            ('Bayelsa', 'Bayelsa'),
                            ('Bauchi', 'Bauchi'),
                            ('Benue', 'Benue'),
                            ('Borno', 'Borno'),
                            ('Cross River', 'Cross River'),
                            ('Delta', 'Delta'),
                            ('Edo', 'Edo'),
                            ('Ebonyi', 'Ebonyi'),
                            ('Ekiti', 'Ekiti'),
                            ('Enugu', 'Enugu'),
                            ('Gombe', 'Gombe'),
                            ('Imo', 'Imo'),
                            ('Jigawa', 'Jigawa'),
                            ('Kaduna', 'Kaduna'),
                            ('Kano', 'Kano'),
                            ('Katsina', 'Katsina'),
                            ('Kebbi', 'Kebbi'),
                            ('Kogi', 'Kogi'),
                            ('Kwara', 'Kwara'),
                            ('Lagos', 'Lagos'),
                            ('Nassawara', 'Nassawara'),
                            ('Niger', 'Niger'),
                            ('Ogun', 'Ogun'),
                            ('Ondo', 'Ondo'),
                            ('Osun', 'Osun'),
                            ('Oyo', 'Oyo'),
                            ('Plateau', 'Plateau'),
                            ('Rivers', 'Rivers'),
                            ('Sokoto', 'Sokoto'),
                            ('Taraba', 'Taraba'),
                            ('Yobe', 'Yobe'),
                            ('Zamfara', 'Zamfara'),
                        ],
                        db_index=True,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    'vicinity',
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    'vicinity_type',
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    'longitude',
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    'latitude',
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    'lga',
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserIdentification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'identity',
                    cloudinary.models.CloudinaryField(
                        max_length=100,
                        null=True,
                        verbose_name='Identification Document',
                    ),
                ),
                ('verified', models.BooleanField(default=False)),
                (
                    'doc_type',
                    models.CharField(
                        choices=[('identity', 'identity')],
                        default='identity',
                        max_length=30,
                    ),
                ),
                ('require_modification', models.BooleanField(default=False)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='identifications',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='api.JobCategory',
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='api.Location'
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='poster',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='api.JobType'
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='api.Job'
            ),
        ),
    ]
