# Generated by Django 2.0.1 on 2018-02-12 04:30
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [('api', '0001_initial')]
    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'slug',
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from='name'
                    ),
                ),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, max_length=400)),
                (
                    'categories',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api.JobCategory',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'status',
                    models.IntegerField(
                        choices=[(0, 'Inactive'), (1, 'Active')],
                        default=1,
                        verbose_name='status',
                    ),
                ),
                (
                    'activate_date',
                    models.DateTimeField(
                        blank=True,
                        help_text='keep empty for an immediate activation',
                        null=True,
                    ),
                ),
                (
                    'deactivate_date',
                    models.DateTimeField(
                        blank=True,
                        help_text='keep empty for indefinite activation',
                        null=True,
                    ),
                ),
                (
                    'heading',
                    models.CharField(db_index=True, max_length=70, null=True),
                ),
                (
                    'slug',
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        max_length=70,
                        populate_from='heading',
                    ),
                ),
                ('description', models.TextField()),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, default=500.0, max_digits=10
                    ),
                ),
                ('booked', models.BooleanField()),
                (
                    'service',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='api.Service',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('status', '-activate_date'), 'abstract': False
            },
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={
                'verbose_name': 'Job Type', 'verbose_name_plural': 'Job Types'
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='provider',
                to='api.ServiceProvider',
            ),
        ),
    ]
