# Generated by Django 2.0.1 on 2018-02-12 08:05
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('api', '0003_auto_20180212_0539')]
    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
