# Generated by Django 2.0.1 on 2018-02-17 14:42
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('api', '0004_auto_20180212_0905')]
    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='parent_category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='api.JobCategory',
            ),
        )
    ]
