# Generated by Django 2.0.1 on 2018-03-24 19:54
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('api', '0006_auto_20180320_2302')]
    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('Provider', 'provider'), ('Customer', 'customer')],
                default='customer',
                max_length=256,
            ),
        ),
    ]
