# Generated by Django 2.0.1 on 2018-03-25 06:59
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('api', '0007_auto_20180324_2054')]
    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        )
    ]
