# Generated by Django 2.0.1 on 2018-03-25 16:18
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('api', '0008_service_image')]
    operations = [
        migrations.AlterModelOptions(name='serviceprovider', options={}),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('provider', 'provider'), ('customer', 'customer')],
                default='customer',
                max_length=256,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='serviceprovider', unique_together={('user', 'service')}
        ),
    ]
