# Generated by Django 2.0.1 on 2018-03-26 08:17
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('api', '0009_auto_20180325_1718')]
    operations = [
        migrations.AddField(
            model_name='job',
            name='service',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='api.Service',
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='num_to_apply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
