# Generated by Django 2.0.1 on 2018-04-03 15:50
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('api', '0013_auto_20180403_1528')]
    operations = [
        migrations.RenameModel(old_name='Sesion', new_name='Session')
    ]
