# Generated by Django 2.0.1 on 2018-04-03 16:17
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('api', '0014_auto_20180403_1650')]
    operations = [
        migrations.RenameModel(
            old_name='ServiceExtras', new_name='ServiceExtra'
        ),
        migrations.AddField(
            model_name='booking',
            name='service_extras',
            field=models.ManyToManyField(to='api.ServiceExtra'),
        ),
    ]
