# Generated by Django 2.0.1 on 2018-04-09 06:13
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('api', '0015_auto_20180403_1717')]
    operations = [
        migrations.AddField(
            model_name='serviceextra',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='serviceextra',
            name='unit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
