# Generated by Django 2.0.1 on 2018-04-24 07:36
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [('api', '0016_auto_20180409_0713')]
    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='service',
                to='api.Service',
            ),
        ),
        migrations.AddField(
            model_name='session',
            name='booking',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='api.Booking',
            ),
        ),
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(
                default=datetime.datetime(
                    2018, 4, 24, 7, 36, 58, 462704, tzinfo=utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceextra',
            name='unit',
            field=models.CharField(
                blank=True, default='', max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name='session', name='start', field=models.DateField()
        ),
    ]
