# Generated by Django 2.0.1 on 2018-04-24 14:43
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('api', '0017_auto_20180424_0836')]
    operations = [
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='provider',
                to='api.ServiceProvider',
            ),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(
                choices=[
                    (1, 'not started'),
                    (2, 'started'),
                    (3, 'completed'),
                    (5, 'cancelled'),
                ],
                default=4,
            ),
        ),
    ]
