# Generated by Django 2.0.1 on 2018-05-04 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180424_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='heading',
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=250, populate_from='heading'),
        ),
        migrations.AlterField(
            model_name='session',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.Booking'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.IntegerField(choices=[(1, 'not started'), (2, 'started'), (3, 'completed'), (5, 'cancelled'), (4, 'pending')], default=1),
        ),
    ]
